// Build instructions:
// as -o compiler.o compiler.s
// ld -o 

 // compiler.o
// ./compiler

.global _start
.section .data

// Simulated compiler input string: "int x = 5;"
source_code:
    .ascii "int x = 5;\n"
source_len = . - source_code

// Compiler internal lookup tokens
token_int:
    .ascii "int"

// Format templates for compiler console output
msg_scanning:
    .ascii "Scanning: "
msg_scanning_len = . - msg_scanning

msg_output:
    .ascii "Generated Bytecode: BIPUSH -> "
msg_output_len = . - msg_output

.section .bss
    .lcomm target_byte, 1   // Buffer to hold the isolated value character ('5')
    .lcomm newline, 1       // Buffer for formatting

.section .text
_start:
    // --- STAGE 1: PRINT STATUS MESSAGE ---
    mov x0, #1              // stdout file descriptor
    ldr x1, =msg_scanning   // Message pointer
    ldr x2, =msg_scanning_len
    mov x8, #64             // Linux write system call ID
    svc #0                  // Execute system call

    mov x0, #1              
    ldr x1, =source_code    // Echo the source code line
    ldr x2, =source_code_len
    mov x8, #64             
    svc #0

    // --- STAGE 2: LEXICAL VALIDATION ("int") ---
    ldr x0, =source_code
    ldr x1, =token_int
    
    ldrb w2, [x0, #0]       // Read 'i'
    ldrb w3, [x1, #0]
    cmp w2, w3
    b.ne error_exit

    ldrb w2, [x0, #1]       // Read 'n'
    ldrb w3, [x1, #1]
    cmp w2, w3
    b.ne error_exit

    ldrb w2, [x0, #2]       // Read 't'
    ldrb w3, [x1, #2]
    cmp w2, w3
    b.ne error_exit

    // --- STAGE 3: EXTRACT VARIABLE VALUE ---
    // In "int x = 5;", index 8 contains the value '5'
    ldrb w4, [x0, #8]       
    ldr x5, =target_byte
    strb w4, [x5]           // Store '5' into the target_byte buffer

    // --- STAGE 4: OUTPUT COMPILER RESULT ---
    mov x0, #1              
    ldr x1, =msg_output     // Print "Generated Bytecode: BIPUSH -> "
    ldr x2, =msg_output_len
    mov x8, #64             
    svc #0

    mov x0, #1              
    ldr x1, =target_byte    // Print the extracted digit ('5')
    mov x2, #1              // 1 byte long
    mov x8, #64             
    svc #0

    // Print a trailing newline for clean console layout
    mov w6, #10             // ASCII code for '\n'
    ldr x7, =newline
    strb w6, [x7]
    mov x0, #1
    mov x1, x7
    mov x2, #1
    mov x8, #64
    svc #0

success_exit:
    mov x0, #0              // Return code 0
    mov x8, #93             // Linux exit system call ID
    svc #0

error_exit:
    mov x0, #1              // Return code 1 (Syntax error)
    mov x8, #93             
    svc #0 
